import React, { createContext, useContext, useEffect, useMemo, useState } from 'react';
import { createRoot } from 'react-dom/client';
import { BrowserRouter, Routes, Route, Navigate, Link, NavLink, useNavigate, useLocation } from 'react-router-dom';
import { LayoutDashboard, BookOpen, BriefcaseBusiness, LogIn, LogOut, Menu, X, User, ShieldCheck, Search, ArrowRight, Clock3, Users, CheckCircle2, LifeBuoy, BarChart3, Plus, Pencil, Trash2, MessageSquare, GraduationCap } from 'lucide-react';
import { api, get, post, put, patch, del } from './api';
import './styles.css';

const AuthContext = createContext(null);
function useAuth(){ return useContext(AuthContext); }

function AuthProvider({ children }) {
  const [user,setUser] = useState(null); const [loading,setLoading]=useState(true);
  useEffect(()=>{ if(localStorage.getItem('token')) get('/auth/me').then(d=>setUser(d.user)).catch(()=>localStorage.removeItem('token')).finally(()=>setLoading(false)); else setLoading(false); },[]);
  const login=async(data)=>{const r=await post('/auth/login',data); localStorage.setItem('token',r.token); setUser(r.user); return r;};
  const register=async(data)=>{const r=await post('/auth/register',data); localStorage.setItem('token',r.token); setUser(r.user); return r;};
  const logout=()=>{localStorage.removeItem('token');setUser(null);};
  return <AuthContext.Provider value={{user,loading,login,register,logout}}>{children}</AuthContext.Provider>;
}

function App(){return <AuthProvider><BrowserRouter><Shell/><Toasts/></BrowserRouter></AuthProvider>}
let toastFn = null;
function notify(message,type='success'){ if(toastFn) toastFn({message,type}); }
function Toasts(){const [toast,setToast]=useState(null); useEffect(()=>{toastFn=setToast; return()=>{toastFn=null}},[]); useEffect(()=>{if(toast){const t=setTimeout(()=>setToast(null),3000);return()=>clearTimeout(t)}},[toast]); return toast?<div className={`toast ${toast.type}`}>{toast.message}</div>:null}

function Shell(){
 const {user,logout}=useAuth(); const [open,setOpen]=useState(false); const navigate=useNavigate();
 const nav=[['Home','/',''],['Programs','/programs',''],['Services','/services',''],...(user?[['Dashboard',user.role==='admin'?'/admin':'/dashboard','']]:[])];
 return <div className="app-shell"><header className="navbar"><Link className="brand" to="/"><span className="brand-mark">T</span><span>TechLearn<span className="brand-accent">Hub</span></span></Link><button className="mobile-menu" onClick={()=>setOpen(!open)}>{open?<X/>:<Menu/>}</button><nav className={open?'nav open':'nav'}>{nav.map(([label,path])=><NavLink key={path} onClick={()=>setOpen(false)} className={({isActive})=>isActive?'active':''} to={path}>{label}</NavLink>)}{user?<><span className="nav-user"><User size={16}/>{user.name.split(' ')[0]}</span><button className="btn btn-ghost btn-small" onClick={()=>{logout();navigate('/')}}><LogOut size={15}/> Logout</button></>:<Link className="btn btn-primary btn-small" to="/login">Sign in <ArrowRight size={15}/></Link>}</nav></header><main><Routes><Route path="/" element={<Home/>}/><Route path="/programs" element={<Programs/>}/><Route path="/services" element={<Services/>}/><Route path="/login" element={user?<Navigate to={user.role==='admin'?'/admin':'/dashboard'}/>:<Login/>}/><Route path="/register" element={user?<Navigate to="/dashboard"/>:<Register/>}/><Route path="/dashboard" element={<Protected><UserDashboard/></Protected>}/><Route path="/admin" element={<Protected admin><AdminDashboard/></Protected>}/><Route path="*" element={<NotFound/>}/></Routes></main><footer><div><strong>TechLearnHub</strong><p>Technology learning, progress and support in one place.</p></div><div className="footer-links"><Link to="/programs">Programs</Link><Link to="/services">Services</Link><Link to="/login">Login</Link></div><span>© 2026 TechLearnHub</span></footer></div>
}
function Protected({children,admin=false}){const {user,loading}=useAuth(); if(loading)return <Loader/>; if(!user)return <Navigate to="/login" replace/>; if(admin&&user.role!=='admin')return <Navigate to="/dashboard" replace/>; return children;}
function Loader(){return <div className="center"><div className="spinner"/></div>}
function SectionTitle({eyebrow,title,description,action}){return <div className="section-head"><div><span className="eyebrow">{eyebrow}</span><h2>{title}</h2>{description&&<p>{description}</p>}</div>{action}</div>}
function Stat({icon:Icon,label,value}){return <div className="stat"><div className="stat-icon"><Icon size={21}/></div><div><strong>{value}</strong><span>{label}</span></div></div>}

function Home(){const [programs,setPrograms]=useState([]); const [services,setServices]=useState([]); useEffect(()=>{Promise.all([get('/programs'),get('/services')]).then(([p,s])=>{setPrograms(p.programs.slice(0,3));setServices(s.services.slice(0,3))})},[]); return <>
<section className="hero"><div className="hero-copy"><span className="eyebrow">LEARN • BUILD • GROW</span><h1>Build the skills that move your <span>career forward.</span></h1><p>Explore technology programs, track your learning progress and get practical support from one simple platform.</p><div className="hero-actions"><Link to="/programs" className="btn btn-primary">Explore programs <ArrowRight size={17}/></Link><Link to="/register" className="btn btn-outline">Create free account</Link></div><div className="hero-proof"><span><CheckCircle2 size={16}/> Practical projects</span><span><CheckCircle2 size={16}/> Progress tracking</span><span><CheckCircle2 size={16}/> Expert support</span></div></div><div className="hero-card"><div className="hero-card-top"><span className="pill success">LIVE LEARNING</span><span>2026</span></div><div className="learning-preview"><div className="ring"><b>68%</b><small>Progress</small></div><div><strong>Full Stack Web Development</strong><p>Next: REST API integration</p><div className="mini-progress"><i style={{width:'68%'}}/></div></div></div><div className="preview-row"><span><BookOpen size={17}/> 12 weeks</span><span><Users size={17}/> 2.4k learners</span></div></div></section>
<section className="stats-strip"><Stat icon={BookOpen} label="Learning programs" value="12+"/><Stat icon={Users} label="Active learners" value="2.4k"/><Stat icon={BriefcaseBusiness} label="Support services" value="8"/><Stat icon={CheckCircle2} label="Learning completion" value="86%"/></section>
<section className="section"><SectionTitle eyebrow="PROGRAMS" title="Learn by building real things" description="Focused programs designed around practical skills and portfolio-ready outcomes." action={<Link className="text-link" to="/programs">View all <ArrowRight size={16}/></Link>}/><div className="card-grid">{programs.map(p=><ProgramCard key={p.id} program={p}/>)}</div></section>
<section className="section soft"><SectionTitle eyebrow="SERVICES" title="Need help? Start a request" description="Get mentorship, career guidance, project reviews and workshop support." action={<Link className="text-link" to="/services">Explore services <ArrowRight size={16}/></Link>}/><div className="card-grid">{services.map(s=><ServiceCard key={s.id} service={s}/>)}</div></section>
</>}
function ProgramCard({program}){return <article className="card program-card"><div className="card-top"><span className="pill">{program.category}</span><span className="level">{program.level}</span></div><h3>{program.title}</h3><p>{program.description}</p><div className="meta"><span><Clock3 size={15}/>{program.duration}</span><span><User size={15}/>{program.instructor}</span></div><Link to={`/programs`} className="card-link">View program <ArrowRight size={16}/></Link></article>}
function ServiceCard({service}){return <article className="card service-card"><div className="service-icon"><LifeBuoy size={21}/></div><span className="eyebrow">{service.category}</span><h3>{service.title}</h3><p>{service.description}</p><Link to="/services" className="card-link">Request support <ArrowRight size={16}/></Link></article>}

function Programs(){const [programs,setPrograms]=useState([]); const [q,setQ]=useState(''); const [loading,setLoading]=useState(true); const {user}=useAuth(); const [enrolled,setEnrolled]=useState([]); useEffect(()=>{get('/programs').then(d=>setPrograms(d.programs)).finally(()=>setLoading(false)); if(user)get('/enrollments/me').then(d=>setEnrolled(d.enrollments.map(x=>x.program_id)));},[user]); const enroll=async(id)=>{if(!user)return window.location.href='/login'; try{await post('/enrollments',{programId:id});setEnrolled(e=>[...e,id]);notify('You are enrolled successfully.')}catch(e){notify(e.message,'error')}}; const filtered=programs.filter(p=>(p.title+' '+p.description+' '+p.category).toLowerCase().includes(q.toLowerCase())); return <section className="page"><SectionTitle eyebrow="LEARNING CATALOG" title="Technology programs" description="Choose a focused learning path and track your progress from your dashboard."/><div className="toolbar"><div className="search"><Search size={18}/><input value={q} onChange={e=>setQ(e.target.value)} placeholder="Search programs..."/></div><span>{filtered.length} programs</span></div>{loading?<Loader/>:<div className="card-grid">{filtered.map(p=><article className="card program-card" key={p.id}><div className="card-top"><span className="pill">{p.category}</span><span className="level">{p.level}</span></div><h3>{p.title}</h3><p>{p.description}</p><div className="meta"><span><Clock3 size={15}/>{p.duration}</span><span><User size={15}/>{p.instructor}</span></div><button disabled={enrolled.includes(p.id)} onClick={()=>enroll(p.id)} className={`btn ${enrolled.includes(p.id)?'btn-muted':'btn-primary'} full`}>{enrolled.includes(p.id)?'Enrolled':'Enroll now'} {enrolled.includes(p.id)?<CheckCircle2 size={16}/>:<ArrowRight size={16}/>}</button></article>)}</div>}</section>}

function Services(){const [services,setServices]=useState([]); const {user}=useAuth(); const [selected,setSelected]=useState(null); useEffect(()=>{get('/services').then(d=>setServices(d.services))},[]); return <section className="page"><SectionTitle eyebrow="SUPPORT SERVICES" title="Get help when you need it" description="Submit a service request and follow its status from your dashboard."/>{!user&&<div className="callout"><ShieldCheck size={20}/><div><strong>Sign in to request a service.</strong><p>You can browse the catalog without an account, then sign in to submit and track requests.</p></div><Link className="btn btn-primary btn-small" to="/login">Sign in</Link></div>}<div className="card-grid">{services.map(s=><ServiceCard key={s.id} service={s}/>)}</div>{user&&<div className="request-section"><SectionTitle eyebrow="SERVICE REQUEST" title="Submit a request" description="Choose a service and describe what you need."/><RequestForm services={services} selected={selected} setSelected={setSelected}/></div>}</section>}
function RequestForm({services}){const [form,setForm]=useState({serviceId:'',subject:'',message:''}); const [busy,setBusy]=useState(false); const submit=async e=>{e.preventDefault();setBusy(true);try{await post('/service-requests',{...form,serviceId:Number(form.serviceId)});notify('Service request submitted.');setForm({serviceId:'',subject:'',message:''})}catch(err){notify(err.message,'error')}finally{setBusy(false)}}; return <form className="form card" onSubmit={submit}><div className="form-grid"><label>Service<select required value={form.serviceId} onChange={e=>setForm({...form,serviceId:e.target.value})}><option value="">Select a service</option>{services.map(s=><option key={s.id} value={s.id}>{s.title}</option>)}</select></label><label>Subject<input required value={form.subject} onChange={e=>setForm({...form,subject:e.target.value})} placeholder="What do you need help with?"/></label></div><label>Message<textarea required rows="5" value={form.message} onChange={e=>setForm({...form,message:e.target.value})} placeholder="Add useful context about your request..."/></label><button disabled={busy} className="btn btn-primary">{busy?'Submitting...':'Submit request'} <ArrowRight size={16}/></button></form>}

function Login(){const {login}=useAuth(); const nav=useNavigate(); const [form,setForm]=useState({email:'',password:''}); const [error,setError]=useState(''); const submit=async e=>{e.preventDefault();setError('');try{const r=await login(form);nav(r.user.role==='admin'?'/admin':'/dashboard')}catch(e){setError(e.message)}}; return <AuthLayout title="Welcome back" subtitle="Sign in to continue your learning journey."><form className="form auth-form" onSubmit={submit}>{error&&<div className="error-box">{error}</div>}<label>Email<input type="email" required value={form.email} onChange={e=>setForm({...form,email:e.target.value})} placeholder="you@example.com"/></label><label>Password<input type="password" required value={form.password} onChange={e=>setForm({...form,password:e.target.value})} placeholder="••••••••"/></label><button className="btn btn-primary full">Sign in <LogIn size={16}/></button><p className="form-note">Demo: user@example.com / User@123</p><p className="switch">New here? <Link to="/register">Create an account</Link></p></form></AuthLayout>}
function Register(){const {register}=useAuth(); const nav=useNavigate(); const [form,setForm]=useState({name:'',email:'',password:''}); const [error,setError]=useState(''); const submit=async e=>{e.preventDefault();try{const r=await register(form);nav('/dashboard')}catch(e){setError(e.message)}}; return <AuthLayout title="Create your account" subtitle="Save enrollments, track progress and request support."><form className="form auth-form" onSubmit={submit}>{error&&<div className="error-box">{error}</div>}<label>Full name<input required value={form.name} onChange={e=>setForm({...form,name:e.target.value})} placeholder="Your name"/></label><label>Email<input type="email" required value={form.email} onChange={e=>setForm({...form,email:e.target.value})} placeholder="you@example.com"/></label><label>Password<input type="password" minLength="6" required value={form.password} onChange={e=>setForm({...form,password:e.target.value})} placeholder="At least 6 characters"/></label><button className="btn btn-primary full">Create account <ArrowRight size={16}/></button><p className="switch">Already registered? <Link to="/login">Sign in</Link></p></form></AuthLayout>}
function AuthLayout({title,subtitle,children}){return <section className="auth-page"><div className="auth-side"><span className="eyebrow">TECHLEARNHUB</span><h1>Learn. Practice. <span>Progress.</span></h1><p>A focused platform for technology learning, support and measurable progress.</p><div className="auth-features"><span><CheckCircle2/> Practical programs</span><span><CheckCircle2/> Progress tracking</span><span><CheckCircle2/> Service support</span></div></div><div className="auth-box"><div className="auth-heading"><span className="brand-mark">T</span><h2>{title}</h2><p>{subtitle}</p></div>{children}</div></section>}

function UserDashboard(){const {user}=useAuth(); const [data,setData]=useState({enrollments:[],requests:[]}); const load=()=>Promise.all([get('/enrollments/me'),get('/service-requests/me')]).then(([e,r])=>setData({enrollments:e.enrollments,requests:r.requests})); useEffect(()=>{load()},[]); const update=async(id,value)=>{try{await patch(`/enrollments/${id}/progress`,{progress:value});load();notify('Progress updated.')}catch(e){notify(e.message,'error')}}; return <section className="page"><div className="dashboard-heading"><div><span className="eyebrow">MY DASHBOARD</span><h1>Good to see you, {user.name.split(' ')[0]}.</h1><p>Keep your learning moving and stay on top of support requests.</p></div><Link to="/programs" className="btn btn-primary">Explore programs <ArrowRight size={16}/></Link></div><div className="stats-grid"><Stat icon={BookOpen} label="Enrolled programs" value={data.enrollments.length}/><Stat icon={BarChart3} label="Avg. progress" value={data.enrollments.length?Math.round(data.enrollments.reduce((a,b)=>a+b.progress,0)/data.enrollments.length)+'%':'0%'}/><Stat icon={LifeBuoy} label="Service requests" value={data.requests.length}/><Stat icon={CheckCircle2} label="Completed" value={data.enrollments.filter(x=>x.progress===100).length}/></div><div className="dashboard-grid"><div><SectionTitle eyebrow="LEARNING" title="Your programs"/><div className="stack">{data.enrollments.length===0?<Empty text="You have not enrolled in a program yet." link="/programs"/>:data.enrollments.map(e=><div className="progress-card" key={e.id}><div className="progress-main"><div className="program-avatar"><GraduationCap/></div><div><strong>{e.title}</strong><span>{e.category} · {e.duration}</span></div><b>{e.progress}%</b></div><div className="progressbar"><i style={{width:`${e.progress}%`}}/></div><div className="progress-actions"><input type="range" min="0" max="100" value={e.progress} onChange={ev=>update(e.id,Number(ev.target.value))}/><span>Drag to update progress</span></div></div>)}</div></div><div><SectionTitle eyebrow="SUPPORT" title="Recent requests" action={<Link className="text-link" to="/services">New request <Plus size={16}/></Link>}/><div className="stack">{data.requests.length===0?<Empty text="No service requests yet." link="/services"/>:data.requests.slice(0,5).map(r=><div className="request-row" key={r.id}><div className="request-icon"><MessageSquare size={17}/></div><div><strong>{r.subject}</strong><span>{r.service_title}</span></div><span className={`status ${r.status}`}>{r.status.replace('_',' ')}</span></div>)}</div></div></div></section>}
function Empty({text,link}){return <div className="empty"><p>{text}</p><Link to={link} className="btn btn-outline btn-small">Explore</Link></div>}

function AdminDashboard(){const [tab,setTab]=useState('overview'); const [analytics,setAnalytics]=useState(null); const [programs,setPrograms]=useState([]); const [services,setServices]=useState([]); const [requests,setRequests]=useState([]); const [users,setUsers]=useState([]); const load=async()=>{const [a,p,s,r,u]=await Promise.all([get('/admin/analytics'),get('/programs'),get('/services'),get('/admin/requests'),get('/admin/users')]);setAnalytics(a.analytics);setPrograms(p.programs);setServices(s.services);setRequests(r.requests);setUsers(u.users)}; useEffect(()=>{load()},[]); const updateRequest=async(id,status)=>{try{await patch(`/admin/requests/${id}/status`,{status});load();notify('Request status updated.')}catch(e){notify(e.message,'error')}}; return <section className="page"><div className="dashboard-heading"><div><span className="eyebrow">ADMIN CONSOLE</span><h1>Platform overview</h1><p>Manage the catalog, users, enrollments and service requests.</p></div><span className="admin-badge"><ShieldCheck size={16}/> Administrator</span></div><div className="tabs">{[['overview','Overview'],['programs','Programs'],['services','Services'],['requests','Requests'],['users','Users']].map(x=><button key={x[0]} className={tab===x[0]?'active':''} onClick={()=>setTab(x[0])}>{x[1]}</button>)}</div>{tab==='overview'&&<AdminOverview analytics={analytics}/>} {tab==='programs'&&<AdminPrograms programs={programs} reload={load}/>} {tab==='services'&&<AdminServices services={services} reload={load}/>} {tab==='requests'&&<AdminRequests requests={requests} updateRequest={updateRequest}/>} {tab==='users'&&<AdminUsers users={users}/>}</section>}
function AdminOverview({analytics}){if(!analytics)return <Loader/>; return <><div className="stats-grid"><Stat icon={Users} label="Users" value={analytics.users}/><Stat icon={BookOpen} label="Active programs" value={analytics.programs}/><Stat icon={GraduationCap} label="Enrollments" value={analytics.enrollments}/><Stat icon={LifeBuoy} label="Open requests" value={analytics.openRequests}/></div><div className="overview-grid"><div className="card"><div className="card-heading"><h3>Program categories</h3><BarChart3/></div>{analytics.categories.map(c=><div className="bar-row" key={c.category}><span>{c.category}</span><div><i style={{width:`${Math.max(8,(c.count/Math.max(...analytics.categories.map(x=>x.count)))*100)}%`}}/></div><b>{c.count}</b></div>)}</div><div className="card admin-summary"><h3>Platform health</h3><div><span>Completion rate</span><strong>{analytics.enrollments?Math.round(analytics.completedEnrollments/analytics.enrollments*100):0}%</strong></div><div><span>Open support load</span><strong>{analytics.openRequests}</strong></div><div><span>Active catalog</span><strong>{analytics.programs} programs</strong></div></div></div></>}
function AdminPrograms({programs,reload}){const blank={title:'',description:'',category:'Web Development',level:'Intermediate',duration:'8 weeks',instructor:'',status:'active'}; const [form,setForm]=useState(blank); const [editing,setEditing]=useState(null); const save=async e=>{e.preventDefault();try{if(editing)await put(`/programs/${editing}`,form);else await post('/programs',form);setForm(blank);setEditing(null);reload();notify(editing?'Program updated.':'Program created.')}catch(e){notify(e.message,'error')}}; const edit=p=>{setEditing(p.id);setForm({...p})}; const remove=async id=>{if(confirm('Archive this program?')){await del(`/programs/${id}`);reload();notify('Program archived.')}}; return <div className="admin-layout"><form className="card form" onSubmit={save}><div className="card-heading"><h3>{editing?'Edit program':'Add program'}</h3>{editing&&<button type="button" className="icon-btn" onClick={()=>{setEditing(null);setForm(blank)}}><X/></button>}</div>{['title','category','level','duration','instructor'].map(k=><label key={k}>{k[0].toUpperCase()+k.slice(1)}<input required value={form[k]} onChange={e=>setForm({...form,[k]:e.target.value})}/></label>)}<label>Description<textarea required rows="4" value={form.description} onChange={e=>setForm({...form,description:e.target.value})}/></label><button className="btn btn-primary full">{editing?'Save changes':'Add program'} <Plus size={16}/></button></form><div className="stack">{programs.map(p=><div className="admin-item" key={p.id}><div><span className="pill">{p.category}</span><strong>{p.title}</strong><small>{p.duration} · {p.instructor}</small></div><div className="row-actions"><button className="icon-btn" onClick={()=>edit(p)}><Pencil size={16}/></button><button className="icon-btn danger" onClick={()=>remove(p.id)}><Trash2 size={16}/></button></div></div>)}</div></div>}
function AdminServices({services,reload}){const blank={title:'',description:'',category:'Mentorship',status:'active'}; const [form,setForm]=useState(blank); const save=async e=>{e.preventDefault();try{await post('/services',form);setForm(blank);reload();notify('Service created.')}catch(e){notify(e.message,'error')}}; const remove=async id=>{if(confirm('Deactivate this service?')){await del(`/services/${id}`);reload();notify('Service deactivated.')}}; return <div className="admin-layout"><form className="card form" onSubmit={save}><div className="card-heading"><h3>Add service</h3></div><label>Title<input required value={form.title} onChange={e=>setForm({...form,title:e.target.value})}/></label><label>Category<input required value={form.category} onChange={e=>setForm({...form,category:e.target.value})}/></label><label>Description<textarea required rows="5" value={form.description} onChange={e=>setForm({...form,description:e.target.value})}/></label><button className="btn btn-primary full">Add service <Plus size={16}/></button></form><div className="stack">{services.map(s=><div className="admin-item" key={s.id}><div><span className="pill">{s.category}</span><strong>{s.title}</strong><small>{s.description}</small></div><button className="icon-btn danger" onClick={()=>remove(s.id)}><Trash2 size={16}/></button></div>)}</div></div>}
function AdminRequests({requests,updateRequest}){return <div className="table-wrap"><table><thead><tr><th>User</th><th>Service</th><th>Subject</th><th>Status</th><th>Created</th></tr></thead><tbody>{requests.map(r=><tr key={r.id}><td><strong>{r.user_name}</strong><small>{r.user_email}</small></td><td>{r.service_title}</td><td>{r.subject}<small>{r.message}</small></td><td><select className={`status-select ${r.status}`} value={r.status} onChange={e=>updateRequest(r.id,e.target.value)}><option value="pending">Pending</option><option value="in_progress">In progress</option><option value="resolved">Resolved</option><option value="rejected">Rejected</option></select></td><td>{new Date(r.created_at).toLocaleDateString()}</td></tr>)}</tbody></table>{!requests.length&&<Empty text="No requests yet." link="/services"/>}</div>}
function AdminUsers({users}){return <div className="table-wrap"><table><thead><tr><th>User</th><th>Role</th><th>Enrollments</th><th>Joined</th></tr></thead><tbody>{users.map(u=><tr key={u.id}><td><strong>{u.name}</strong><small>{u.email}</small></td><td><span className="pill">{u.role}</span></td><td>{u.enrollment_count}</td><td>{new Date(u.created_at).toLocaleDateString()}</td></tr>)}</tbody></table></div>}
function NotFound(){return <div className="center page"><h1>404</h1><p>That page does not exist.</p><Link to="/" className="btn btn-primary">Back home</Link></div>}

createRoot(document.getElementById('root')).render(<App/>);
